# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtZlSK3VBxJY1nHSKMByMVT5ZJeXcMuR
"""

import pandas as pd
import numpy as np

price=pd.read_csv("/content/train.csv")

price.shape

price.isna().sum()[price.isna().sum()!=0]
price.drop(['PoolQC','Fence','MiscFeature','Alley'],inplace=True,axis=1)

price.isna().sum()[price.isna().sum()!=0]

cat_dtype=price.select_dtypes(include=["object"]).columns

price[cat_dtype]=price[cat_dtype].fillna("Unknown")

from sklearn.preprocessing import OrdinalEncoder
le=OrdinalEncoder()
price[cat_dtype]=le.fit_transform(price[cat_dtype])

int_col=price.select_dtypes(include=["int64","int32","float"]).columns

from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy="mean")
price[int_col]=si.fit_transform(price[int_col])

price.head()

X_train=price.drop(["Id","SalePrice"],axis=1)
y_train=price["SalePrice"]

X_train.head()

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

y_prd=lr.predict(X_train)

from sklearn.metrics import r2_score,root_mean_squared_error
r2_score(y_train,y_prd)

